active-mq:
  broker-url: tcp://localhost:61616
  topic: demo.topic
server:
  port: 8080
  servlet:
#    context-path: /crud

spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    url: jdbc:h2:mem:testdb
app:
  environment: local